services:
  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules # Named volume prevents binary conflicts
    ports:
      - 4321:4321
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  k6-tests:
    entrypoint: '/bin/true'
    build: k6-tests
    volumes:
      - ./k6-tests/tests:/tests
    depends_on:
      - client

volumes:
  node_modules: